### ISSUE TITLE
.Net Tutorial

### ISSUE THREAD

**Issue by ps0077** [jasonjoh/dotnet-tutorial#10]
This Artiacl Is Vry Helpul ..

But In Readme -images inbox Are Differ comapir Current Project . 
And I Want TO Also Crud Operation With Graph Api .. 
please SHare Complete Solution For Do It ..

**Comment by jasonjoh** [comment]
Closing this issue as I'm archiving this sample. We've retired the tutorial that this is based on and we're redirecting to the Microsoft Graph tutorial at https://docs.microsoft.com/graph/tutorials/aspnet. The corresponding GitHub repo is https://github.com/microsoftgraph/msgraph-training-aspnetmvcapp.
