### ISSUE TITLE
AzureOauth.config is missing

### ISSUE THREAD

**Issue by Usman-Sheikh** [jasonjoh/dotnet-tutorial#12]
![image](https://user-images.githubusercontent.com/7095725/43526468-be141b2a-95bd-11e8-9dcb-26e0bc1d4894.png)

please update the code and commit AzureOauth File

**Comment by jasonjoh** [comment]
It is missing by design. That file contains information that should never be shared (app ID and secret). Please follow the README to generate your own version of the file:

https://github.com/jasonjoh/dotnet-tutorial#configure-the-sample
