### ISSUE TITLE
Office 365 URL Redirection and sign in issue 

### ISSUE THREAD

**Issue by sundarmjkImperium** [jasonjoh/dotnet-tutorial#13]
Hi ,
Greetings of the day.

I am just using the sample to get office365 contacts .its working locally but when i deployed or published in Server 
Its not redirecting after login and also the contact is not showing ...
i hope its not logged in .
and redirection also problem.

Error.
An error occurred while processing your request.

If enable debug 

An unhandled exception was generated during the execution of the current web request. Information regarding the origin and location of the exception can be identified using the exception stack trace below.
--

Please Help Me

**Comment by jasonjoh** [comment]
Without any details, I can only guess. If you registered your app following the tutorial, you set the redirect URL as http://localhost. When you deployed to a server, that URL changed, so you need to add that URL as a redirect URL on your app registration.

**Comment by sundarmjk** [comment]
Dear Jasonjoh,

Greetings ,

I added my server url in that 
like https://192.168.X.X/Contact/Contacts 
but its still not working however ..if i redirect after login (i don't know it logged in or not) contacts list is not loaded its says error:

this all happen only deployed ...
in localhost its working fine

**Comment by jasonjoh** [comment]
Ok. There's not enough information for me to give you an answer here. You'll likely need to connect to the server with Visual Studio and debug the failure.
