### ISSUE TITLE
About Tasks

### ISSUE THREAD

**Issue by mtugnoli** [jasonjoh/dotnet-tutorial#14]
Hi,
I follow this sample to get Mail,Contacts,Calendars,

But when try to use it with Tasks (scope = Tasks.Read), this error occour :

You do not have the required permissions to access this item.

Why ?

**Comment by jasonjoh** [comment]
That's not a lot to go on, but I'm guessing you're adding the scope in the config file, and when trying to access tasks via the API you get this error? It's likely you don't have the new scope in your existing access token, so you may need to sign out and sign back in to trigger the consent dialog for the new scope.

**Comment by jasonjoh** [comment]
Closing this issue as I'm archiving this sample. We've retired the tutorial that this is based on and we're redirecting to the Microsoft Graph tutorial at https://docs.microsoft.com/graph/tutorials/aspnet. The corresponding GitHub repo is https://github.com/microsoftgraph/msgraph-training-aspnetmvcapp.
