### ISSUE TITLE
The reply address does not match

### ISSUE THREAD

**Issue by NoelOConnell** [jasonjoh/dotnet-tutorial#2]
Hi, 

I've followed the instructions but can not get it to work correctly.
I keep getting the error : "The reply address 'http://localhost:10800/Home/Authorize' does not match the reply addresses configured for the application"

I get the same result with : 
Microsoft.Office365.OutlookServices-V2.0 version="2.0.1.0"
Microsoft.Office365.OutlookServices-V2.0 version="2.0.0.0"

Microsoft.Experimental.IdentityModel.Clients.ActiveDirectory version="4.0.209160138-alpha"
Microsoft.Experimental.IdentityModel.Clients.ActiveDirectory version="4.0.208020147-alpha"

I've tried various settings like changing case and toggling the "Allow Implicit Flow" option.

Any ideas what it might be?

![error message](https://cloud.githubusercontent.com/assets/966495/12119998/b8060f9e-b3c6-11e5-9ccf-fa4a0b81689e.PNG)

![settings](https://cloud.githubusercontent.com/assets/966495/12120005/bc4f499e-b3c6-11e5-9d68-3f6a9dc4bfc8.PNG)

**Comment by jasonjoh** [comment]
The Azure auth platform is case-sensitive when it compares the redirect URIs. So you have it in all lowercase in your app registration, but the app is using capitals. Try recreating your registration with a redirect URI that uses the same case as the app.

**Comment by NoelOConnell** [comment]
You are correct, I was changing it in the Authorize action but not the SignIn action. Changed it to lowercase and it worked.

In the apps.dev.microsoft.com portal any URL I entered was converted to lowercase.

Thanks for your help.

**Comment by rrubio** [comment]
Guys? i know i'm late to the party, but we in azure could i adjust this? i.e the reply address?

Follow details below to update reply address. Note, you'll need a subscription. Trial version does not provide the sufficient permissions to update.

PS (UPDATE) - https://docs.microsoft.com/en-us/azure/app-service-mobile/app-service-mobile-how-to-configure-active-directory-authentication

**Comment by DanJ210** [comment]
I'm getting this but every solution is for Azure AD when I don't have Azure AD. The company I'm with has regular AD that they provide themselves. All the documentation I find has to do with Azure, where is the docs for doing this on regular AD that's not hosted on Azure?
