### ISSUE TITLE
Error AADSTS50011

### ISSUE THREAD

**Issue by lommez** [jasonjoh/dotnet-tutorial#4]
I receive that error message: "ERROR retrieving token: AADSTS50011: The reply address 'http://localhost:10800/Home/Authorize' does not match the reply addresses configured for the application".
Is that a known bug?
Thanks

**Comment by jasonjoh** [comment]
No, that's not a bug. It's telling you that the redirect URI you configured in your app registration is not correct. You need to make sure that it is `http://localhost:10800/Home/Authorize` **exactly**. It is case-sensitive.

**Comment by lommez** [comment]
Thank you jasonjoh! Now is working perfectly

**Comment by jasonjoh** [comment]
No problem!
