### ISSUE TITLE
Null value at  string userName = ClaimsPrincipal.Current.FindFirst("name").Value;

### ISSUE THREAD

**Issue by fwd079** [jasonjoh/dotnet-tutorial#6]
Hi,
Hope you are fine, I have run into the issue in subject line while following the tutorial.

I am using Visual Studio 2015 on Windows 10.

Firstly, I followed the steps in [this link](https://dev.outlook.com/restapi/tutorial/dotnet) but got stuck on **Step 4**  part **Updated Index action in ./Controllers/HomeController.cs** so I thought I must have missed a step.

So I came here to GitHub, downloaded the solution and restored NuGet packages, ran and it failed on **exactly** the same link as before (see attached file). The line which throws the NullReferenceException is:

`string userName = ClaimsPrincipal.Current.FindFirst("name").Value;`

Please can you check why is this happening? Am I missing a setup-step or any library etc?

Regards.
.
![image](https://cloud.githubusercontent.com/assets/7912632/17831657/ad956bee-66e6-11e6-99af-1181bda15d55.png)

**Comment by jasonjoh** [comment]
Interesting. Are you using an Office 365 account or an Outlook.com account to sign in?

**Comment by fwd079** [comment]
Yeah, sorry for late reply, as I got distracted to other projects. So I managed to get it working (somehow going to other account) and I can log in now, but now I get this yellow message error. Somehow the "From" isn't recognised.

![image](https://cloud.githubusercontent.com/assets/7912632/18819330/90bc0cb4-8386-11e6-8e85-8de57e6cb59b.png)

**Comment by fwd079** [comment]
PS. I can get the contacts and Calendar Items but for Messages it gives me the above error. Even though the constructor is set as:

`Subject = subject;
            ReceivedDateTime = (DateTimeOffset)dateTimeReceived;
            From = from != null ? string.Format("{0} ({1})", from.EmailAddress.Name,
                            from.EmailAddress.Address) : "EMPTY";`

I still get null reference as posted in picture above.

**Comment by fwd079** [comment]
Ha well, it took me 5 minutes to sort that out. I changed the code as below (apparently if From is null then provided Linq doesn't like it.

``````
           ``` var lstMessages = await client.Me.Messages
                                     .OrderByDescending(m => m.ReceivedDateTime)
                                     .Take(10).ExecuteAsync();

            var mailResults = lstMessages.CurrentPage.Select(m => new Models.DisplayMessage(m.Subject, m.ReceivedDateTime, m.From));

            return View(mailResults);
``````

```
```
