### ISSUE TITLE
Not an issue but a question Install-Package Microsoft.Identity.Client -Pre

### ISSUE THREAD

**Issue by fwd079** [jasonjoh/dotnet-tutorial#7]
Hi, sorry dont know how to ask question, but do we still need to do:

Install-Package Microsoft.Identity.Client -Pre

Can we now that time has passed, remove the -Pre at all?

Thank you for reading.

Regards

**Comment by jasonjoh** [comment]
You can check on this at https://www.nuget.org/packages/Microsoft.Identity.Client. It's still in pre-release so as of now, no.
