### ISSUE TITLE
Authentication Phone number used for password reset

### ISSUE THREAD

**Issue by twcarnahan** [jasonjoh/dotnet-tutorial#9]
We are attempting to use the Phone Number that is used for password reset but can not get it using Claims and it just seems not to be in the Azure directory as it's not the same as mobile number. 
We opened a case in stack flow - http://stackoverflow.com/questions/43573292/get-azure-password-reset-authentication-phone-attribute-using-microsoft-graph-library; but there is no answer - can you point us in the correct direction. 
Vr, Tim:

**Comment by jasonjoh** [comment]
Sorry I'm not sure what the answer is there. I'll ask the Azure folks to look at your StackOverflow post.
